# Generated by Django 3.1.5 on 2021-01-10 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('roll', models.PositiveIntegerField()),
                ('phone', models.CharField(max_length=14)),
                ('email', models.EmailField(blank=True, max_length=60, null=True, unique=True)),
            ],
        ),
    ]
