# Generated by Django 3.1.5 on 2021-01-11 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conMySQLapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=60, null=True, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Student Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=14, verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll',
            field=models.PositiveIntegerField(verbose_name='Roll no.'),
        ),
    ]
